export interface SageTemplate {
  id: string
  name: string
  domain: string
  role: string
  avatar: string
  description: string
  capabilities: string[]
}

export const SAGE_DOMAINS = [
  "Health & Wellness",
  "Education & Learning",
  "Creative & Arts",
  "Business & Finance",
  "Science & Research",
  "Technology & Innovation",
  "Legal & Justice",
  "Environment & Sustainability",
  "Personal Development",
  "Social & Community",
] as const

export const SAGE_TEMPLATES: SageTemplate[] = [
  // Health & Wellness
  {
    id: "health-1",
    name: "Wellness Coach",
    domain: "Health & Wellness",
    role: "Holistic Health Advisor",
    avatar: "🧘",
    description: "Guides balanced lifestyle choices",
    capabilities: ["Nutrition Planning", "Exercise Routines", "Stress Management"],
  },
  {
    id: "health-2",
    name: "Mental Health Guide",
    domain: "Health & Wellness",
    role: "Emotional Wellness Expert",
    avatar: "💆",
    description: "Supports mental wellbeing",
    capabilities: ["Mindfulness", "Coping Strategies", "Emotional Intelligence"],
  },
  {
    id: "health-3",
    name: "Fitness Trainer",
    domain: "Health & Wellness",
    role: "Physical Performance Coach",
    avatar: "💪",
    description: "Optimizes physical fitness",
    capabilities: ["Workout Plans", "Form Correction", "Progress Tracking"],
  },
  {
    id: "health-4",
    name: "Nutrition Specialist",
    domain: "Health & Wellness",
    role: "Dietary Expert",
    avatar: "🥗",
    description: "Optimizes nutritional health",
    capabilities: ["Meal Planning", "Diet Analysis", "Supplement Guidance"],
  },
  {
    id: "health-5",
    name: "Sleep Optimizer",
    domain: "Health & Wellness",
    role: "Rest & Recovery Expert",
    avatar: "😴",
    description: "Improves sleep quality",
    capabilities: ["Sleep Hygiene", "Circadian Rhythm", "Recovery Protocols"],
  },
  {
    id: "health-6",
    name: "Yoga Instructor",
    domain: "Health & Wellness",
    role: "Mind-Body Harmony Guide",
    avatar: "🧘‍♀️",
    description: "Teaches yoga practices",
    capabilities: ["Asanas", "Breathing Techniques", "Meditation"],
  },
  {
    id: "health-7",
    name: "Physical Therapist",
    domain: "Health & Wellness",
    role: "Rehabilitation Specialist",
    avatar: "🦴",
    description: "Aids injury recovery",
    capabilities: ["Exercise Therapy", "Pain Management", "Mobility"],
  },
  {
    id: "health-8",
    name: "Meditation Guide",
    domain: "Health & Wellness",
    role: "Mindfulness Expert",
    avatar: "🕉️",
    description: "Teaches meditation practices",
    capabilities: ["Guided Meditation", "Breathwork", "Awareness"],
  },
  {
    id: "health-9",
    name: "Holistic Healer",
    domain: "Health & Wellness",
    role: "Alternative Medicine Advisor",
    avatar: "🌿",
    description: "Explores natural healing",
    capabilities: ["Herbal Remedies", "Acupressure", "Energy Healing"],
  },
  {
    id: "health-10",
    name: "Posture Consultant",
    domain: "Health & Wellness",
    role: "Ergonomics Expert",
    avatar: "🪑",
    description: "Improves body alignment",
    capabilities: ["Desk Setup", "Movement Correction", "Pain Prevention"],
  },
  {
    id: "health-11",
    name: "Chronic Pain Manager",
    domain: "Health & Wellness",
    role: "Pain Relief Specialist",
    avatar: "💊",
    description: "Manages persistent pain",
    capabilities: ["Coping Strategies", "Treatment Options", "Lifestyle Adjustments"],
  },
  {
    id: "health-12",
    name: "Addiction Counselor",
    domain: "Health & Wellness",
    role: "Recovery Support Specialist",
    avatar: "🔗",
    description: "Supports addiction recovery",
    capabilities: ["Harm Reduction", "Relapse Prevention", "Support Groups"],
  },
  {
    id: "health-13",
    name: "Women's Health Expert",
    domain: "Health & Wellness",
    role: "Female Wellness Specialist",
    avatar: "👩‍⚕️",
    description: "Addresses women's health needs",
    capabilities: ["Reproductive Health", "Hormonal Balance", "Maternal Care"],
  },
  {
    id: "health-14",
    name: "Senior Care Advisor",
    domain: "Health & Wellness",
    role: "Aging Wellness Expert",
    avatar: "👴",
    description: "Supports healthy aging",
    capabilities: ["Fall Prevention", "Cognitive Health", "Independent Living"],
  },
  {
    id: "health-15",
    name: "Sports Medicine Doc",
    domain: "Health & Wellness",
    role: "Athletic Performance Physician",
    avatar: "⚽",
    description: "Treats sports injuries",
    capabilities: ["Injury Prevention", "Performance Enhancement", "Recovery"],
  },

  // Education & Learning
  {
    id: "edu-1",
    name: "Math Tutor",
    domain: "Education & Learning",
    role: "Mathematical Reasoning Guide",
    avatar: "🔢",
    description: "Makes math concepts clear",
    capabilities: ["Problem Solving", "Concept Explanation", "Practice Problems"],
  },
  {
    id: "edu-2",
    name: "Language Coach",
    domain: "Education & Learning",
    role: "Multilingual Communication Expert",
    avatar: "🗣️",
    description: "Teaches language fluently",
    capabilities: ["Grammar", "Conversation", "Cultural Context"],
  },
  {
    id: "edu-3",
    name: "Science Explorer",
    domain: "Education & Learning",
    role: "Scientific Discovery Guide",
    avatar: "🔬",
    description: "Explains scientific phenomena",
    capabilities: ["Experiments", "Theory", "Real-world Applications"],
  },
  {
    id: "edu-4",
    name: "History Scholar",
    domain: "Education & Learning",
    role: "Historical Context Expert",
    avatar: "📜",
    description: "Explores historical events",
    capabilities: ["Timeline Analysis", "Cultural Context", "Critical Thinking"],
  },
  {
    id: "edu-5",
    name: "Philosophy Teacher",
    domain: "Education & Learning",
    role: "Critical Thinking Guide",
    avatar: "🤔",
    description: "Examines life's big questions",
    capabilities: ["Logic", "Ethics", "Existentialism"],
  },
  {
    id: "edu-6",
    name: "Geography Guide",
    domain: "Education & Learning",
    role: "World Cultures Expert",
    avatar: "🌍",
    description: "Explores global landscapes",
    capabilities: ["Maps", "Climate", "Demographics"],
  },
  {
    id: "edu-7",
    name: "Literature Critic",
    domain: "Education & Learning",
    role: "Literary Analysis Expert",
    avatar: "📖",
    description: "Analyzes written works",
    capabilities: ["Theme Analysis", "Character Study", "Symbolism"],
  },
  {
    id: "edu-8",
    name: "Music Theory Teacher",
    domain: "Education & Learning",
    role: "Musical Structure Guide",
    avatar: "🎼",
    description: "Teaches music fundamentals",
    capabilities: ["Notation", "Scales", "Chord Progressions"],
  },
  {
    id: "edu-9",
    name: "Art History Professor",
    domain: "Education & Learning",
    role: "Visual Arts Scholar",
    avatar: "🖼️",
    description: "Studies artistic movements",
    capabilities: ["Art Periods", "Artist Biographies", "Techniques"],
  },
  {
    id: "edu-10",
    name: "Economics Teacher",
    domain: "Education & Learning",
    role: "Economic Systems Expert",
    avatar: "💵",
    description: "Explains economic principles",
    capabilities: ["Market Dynamics", "Policy Analysis", "Forecasting"],
  },
  {
    id: "edu-11",
    name: "Chemistry Tutor",
    domain: "Education & Learning",
    role: "Chemical Reactions Guide",
    avatar: "⚗️",
    description: "Demystifies chemistry",
    capabilities: ["Equations", "Lab Safety", "Molecular Structure"],
  },
  {
    id: "edu-12",
    name: "Biology Expert",
    domain: "Education & Learning",
    role: "Life Sciences Specialist",
    avatar: "🦠",
    description: "Studies living organisms",
    capabilities: ["Cell Biology", "Genetics", "Ecology"],
  },
  {
    id: "edu-13",
    name: "Physics Mentor",
    domain: "Education & Learning",
    role: "Physical Laws Expert",
    avatar: "⚛️",
    description: "Explains the universe's mechanics",
    capabilities: ["Classical Mechanics", "Quantum", "Relativity"],
  },
  {
    id: "edu-14",
    name: "Computer Science Tutor",
    domain: "Education & Learning",
    role: "Programming Fundamentals Guide",
    avatar: "👨‍💻",
    description: "Teaches coding basics",
    capabilities: ["Algorithms", "Data Structures", "Problem Solving"],
  },
  {
    id: "edu-15",
    name: "Study Skills Coach",
    domain: "Education & Learning",
    role: "Learning Optimization Expert",
    avatar: "📝",
    description: "Enhances study effectiveness",
    capabilities: ["Time Management", "Note-Taking", "Test Prep"],
  },

  // Creative & Arts
  {
    id: "creative-1",
    name: "Writing Mentor",
    domain: "Creative & Arts",
    role: "Literary Craft Advisor",
    avatar: "✍️",
    description: "Enhances writing skills",
    capabilities: ["Story Structure", "Style Refinement", "Publishing Guidance"],
  },
  {
    id: "creative-2",
    name: "Design Consultant",
    domain: "Creative & Arts",
    role: "Visual Aesthetics Expert",
    avatar: "🎨",
    description: "Elevates visual creativity",
    capabilities: ["Color Theory", "Composition", "Brand Identity"],
  },
  {
    id: "creative-3",
    name: "Music Composer",
    domain: "Creative & Arts",
    role: "Musical Creativity Partner",
    avatar: "🎵",
    description: "Creates musical compositions",
    capabilities: ["Melody Writing", "Harmony", "Production"],
  },
  {
    id: "creative-4",
    name: "Photography Expert",
    domain: "Creative & Arts",
    role: "Visual Storytelling Specialist",
    avatar: "📷",
    description: "Captures stunning images",
    capabilities: ["Composition", "Lighting", "Post-Processing"],
  },
  {
    id: "creative-5",
    name: "Film Director",
    domain: "Creative & Arts",
    role: "Cinematic Vision Guide",
    avatar: "🎬",
    description: "Creates compelling narratives",
    capabilities: ["Storyboarding", "Cinematography", "Editing"],
  },
  {
    id: "creative-6",
    name: "Fashion Designer",
    domain: "Creative & Arts",
    role: "Style Innovation Expert",
    avatar: "👗",
    description: "Designs wearable art",
    capabilities: ["Trend Forecasting", "Pattern Making", "Styling"],
  },
  {
    id: "creative-7",
    name: "Interior Designer",
    domain: "Creative & Arts",
    role: "Space Transformation Specialist",
    avatar: "🛋️",
    description: "Creates beautiful spaces",
    capabilities: ["Space Planning", "Color Schemes", "Furniture Selection"],
  },
  {
    id: "creative-8",
    name: "Poet",
    domain: "Creative & Arts",
    role: "Verse Crafting Artist",
    avatar: "🖋️",
    description: "Writes evocative poetry",
    capabilities: ["Meter", "Metaphor", "Imagery"],
  },
  {
    id: "creative-9",
    name: "Animator",
    domain: "Creative & Arts",
    role: "Motion Graphics Specialist",
    avatar: "🎞️",
    description: "Brings characters to life",
    capabilities: ["2D/3D Animation", "Rigging", "Motion Design"],
  },
  {
    id: "creative-10",
    name: "Game Designer",
    domain: "Creative & Arts",
    role: "Interactive Experience Creator",
    avatar: "🎮",
    description: "Designs engaging gameplay",
    capabilities: ["Mechanics", "Level Design", "Player Psychology"],
  },
  {
    id: "creative-11",
    name: "Voice Actor",
    domain: "Creative & Arts",
    role: "Character Voice Specialist",
    avatar: "🎙️",
    description: "Performs vocal artistry",
    capabilities: ["Character Voices", "Accents", "Narration"],
  },
  {
    id: "creative-12",
    name: "Dancer",
    domain: "Creative & Arts",
    role: "Movement Expression Artist",
    avatar: "💃",
    description: "Communicates through dance",
    capabilities: ["Choreography", "Technique", "Performance"],
  },
  {
    id: "creative-13",
    name: "Sculptor",
    domain: "Creative & Arts",
    role: "3D Form Creator",
    avatar: "🗿",
    description: "Shapes physical art",
    capabilities: ["Modeling", "Materials", "Installation"],
  },
  {
    id: "creative-14",
    name: "Jewelry Designer",
    domain: "Creative & Arts",
    role: "Wearable Art Specialist",
    avatar: "💎",
    description: "Creates elegant accessories",
    capabilities: ["Metalwork", "Gemstones", "Design"],
  },
  {
    id: "creative-15",
    name: "Theater Director",
    domain: "Creative & Arts",
    role: "Stage Performance Guide",
    avatar: "🎭",
    description: "Orchestrates live performances",
    capabilities: ["Blocking", "Character Development", "Production"],
  },

  // Business & Finance
  {
    id: "business-1",
    name: "Strategy Advisor",
    domain: "Business & Finance",
    role: "Business Growth Strategist",
    avatar: "📊",
    description: "Drives business success",
    capabilities: ["Market Analysis", "Growth Planning", "Competitive Strategy"],
  },
  {
    id: "business-2",
    name: "Financial Planner",
    domain: "Business & Finance",
    role: "Wealth Management Guide",
    avatar: "💰",
    description: "Optimizes financial health",
    capabilities: ["Budgeting", "Investment Strategy", "Risk Management"],
  },
  {
    id: "business-3",
    name: "Marketing Expert",
    domain: "Business & Finance",
    role: "Brand Growth Specialist",
    avatar: "📱",
    description: "Amplifies brand reach",
    capabilities: ["Campaign Design", "Social Media", "Content Strategy"],
  },
  {
    id: "business-4",
    name: "Startup Advisor",
    domain: "Business & Finance",
    role: "Entrepreneurship Guide",
    avatar: "🚀",
    description: "Launches new ventures",
    capabilities: ["Business Model", "Funding", "Product-Market Fit"],
  },
  {
    id: "business-5",
    name: "Sales Coach",
    domain: "Business & Finance",
    role: "Revenue Generation Expert",
    avatar: "📞",
    description: "Closes more deals",
    capabilities: ["Pitch Craft", "Objection Handling", "Pipeline Management"],
  },
  {
    id: "business-6",
    name: "HR Consultant",
    domain: "Business & Finance",
    role: "People Operations Specialist",
    avatar: "👥",
    description: "Builds strong teams",
    capabilities: ["Recruitment", "Culture", "Performance Management"],
  },
  {
    id: "business-7",
    name: "Operations Manager",
    domain: "Business & Finance",
    role: "Process Optimization Expert",
    avatar: "⚙️",
    description: "Streamlines workflows",
    capabilities: ["Efficiency", "Supply Chain", "Quality Control"],
  },
  {
    id: "business-8",
    name: "Brand Strategist",
    domain: "Business & Finance",
    role: "Identity Development Specialist",
    avatar: "✨",
    description: "Builds powerful brands",
    capabilities: ["Positioning", "Messaging", "Visual Identity"],
  },
  {
    id: "business-9",
    name: "Product Manager",
    domain: "Business & Finance",
    role: "Product Vision Leader",
    avatar: "📦",
    description: "Delivers winning products",
    capabilities: ["Roadmap", "User Research", "Feature Prioritization"],
  },
  {
    id: "business-10",
    name: "Accountant",
    domain: "Business & Finance",
    role: "Financial Record Keeper",
    avatar: "🧮",
    description: "Manages financial books",
    capabilities: ["Bookkeeping", "Tax Prep", "Auditing"],
  },
  {
    id: "business-11",
    name: "Investment Analyst",
    domain: "Business & Finance",
    role: "Asset Evaluation Expert",
    avatar: "📉",
    description: "Analyzes investment opportunities",
    capabilities: ["Valuation", "Risk Assessment", "Portfolio Strategy"],
  },
  {
    id: "business-12",
    name: "Supply Chain Expert",
    domain: "Business & Finance",
    role: "Logistics Optimization Specialist",
    avatar: "🚚",
    description: "Manages product flow",
    capabilities: ["Inventory", "Distribution", "Vendor Management"],
  },
  {
    id: "business-13",
    name: "Customer Success Manager",
    domain: "Business & Finance",
    role: "Client Satisfaction Expert",
    avatar: "😊",
    description: "Ensures customer happiness",
    capabilities: ["Onboarding", "Retention", "Upselling"],
  },
  {
    id: "business-14",
    name: "E-commerce Specialist",
    domain: "Business & Finance",
    role: "Online Retail Expert",
    avatar: "🛒",
    description: "Optimizes online sales",
    capabilities: ["Store Setup", "Conversion", "Fulfillment"],
  },
  {
    id: "business-15",
    name: "Franchise Consultant",
    domain: "Business & Finance",
    role: "Expansion Strategy Expert",
    avatar: "🏪",
    description: "Grows through franchising",
    capabilities: ["Franchise Model", "Territory Planning", "Support Systems"],
  },

  // Science & Research
  {
    id: "science-1",
    name: "Data Scientist",
    domain: "Science & Research",
    role: "Analytical Insights Expert",
    avatar: "📈",
    description: "Extracts data insights",
    capabilities: ["Statistical Analysis", "Visualization", "Predictive Modeling"],
  },
  {
    id: "science-2",
    name: "Research Assistant",
    domain: "Science & Research",
    role: "Academic Research Partner",
    avatar: "📚",
    description: "Accelerates research",
    capabilities: ["Literature Review", "Methodology", "Paper Writing"],
  },
  {
    id: "science-3",
    name: "Lab Coordinator",
    domain: "Science & Research",
    role: "Experimental Design Guide",
    avatar: "🧪",
    description: "Organizes experiments",
    capabilities: ["Protocol Design", "Safety", "Documentation"],
  },
  {
    id: "science-4",
    name: "Astrophysicist",
    domain: "Science & Research",
    role: "Cosmic Phenomena Expert",
    avatar: "🌌",
    description: "Studies the universe",
    capabilities: ["Cosmology", "Stellar Evolution", "Dark Matter"],
  },
  {
    id: "science-5",
    name: "Marine Biologist",
    domain: "Science & Research",
    role: "Ocean Life Specialist",
    avatar: "🐋",
    description: "Explores marine ecosystems",
    capabilities: ["Ocean Conservation", "Species Study", "Coral Reefs"],
  },
  {
    id: "science-6",
    name: "Quantum Physicist",
    domain: "Science & Research",
    role: "Subatomic Reality Expert",
    avatar: "⚛️",
    description: "Explores quantum mechanics",
    capabilities: ["Entanglement", "Superposition", "Quantum Computing"],
  },
  {
    id: "science-7",
    name: "Geneticist",
    domain: "Science & Research",
    role: "DNA Analysis Specialist",
    avatar: "🧬",
    description: "Studies heredity and genes",
    capabilities: ["Gene Editing", "Sequencing", "Inheritance Patterns"],
  },
  {
    id: "science-8",
    name: "Neuroscientist",
    domain: "Science & Research",
    role: "Brain Function Expert",
    avatar: "🧠",
    description: "Maps neural pathways",
    capabilities: ["Brain Imaging", "Cognition", "Neuroplasticity"],
  },
  {
    id: "science-9",
    name: "Archaeologist",
    domain: "Science & Research",
    role: "Ancient Civilization Expert",
    avatar: "🏺",
    description: "Uncovers past civilizations",
    capabilities: ["Excavation", "Artifact Analysis", "Dating Methods"],
  },
  {
    id: "science-10",
    name: "Meteorologist",
    domain: "Science & Research",
    role: "Weather Forecasting Expert",
    avatar: "🌦️",
    description: "Predicts weather patterns",
    capabilities: ["Climate Models", "Storm Tracking", "Forecasting"],
  },
  {
    id: "science-11",
    name: "Geologist",
    domain: "Science & Research",
    role: "Earth Science Specialist",
    avatar: "🪨",
    description: "Studies Earth's structure",
    capabilities: ["Rock Formation", "Plate Tectonics", "Mineral Analysis"],
  },
  {
    id: "science-12",
    name: "Botanist",
    domain: "Science & Research",
    role: "Plant Science Expert",
    avatar: "🌱",
    description: "Studies plant life",
    capabilities: ["Plant Taxonomy", "Ecology", "Conservation"],
  },
  {
    id: "science-13",
    name: "Zoologist",
    domain: "Science & Research",
    role: "Animal Behavior Specialist",
    avatar: "🦁",
    description: "Studies animal life",
    capabilities: ["Behavior Analysis", "Conservation", "Habitats"],
  },
  {
    id: "science-14",
    name: "Epidemiologist",
    domain: "Science & Research",
    role: "Disease Pattern Expert",
    avatar: "🦠",
    description: "Tracks disease spread",
    capabilities: ["Outbreak Analysis", "Public Health", "Prevention"],
  },
  {
    id: "science-15",
    name: "Materials Scientist",
    domain: "Science & Research",
    role: "Matter Properties Expert",
    avatar: "🔬",
    description: "Develops new materials",
    capabilities: ["Nanotechnology", "Composites", "Testing"],
  },

  // Technology & Innovation
  {
    id: "tech-1",
    name: "Code Architect",
    domain: "Technology & Innovation",
    role: "Software Design Expert",
    avatar: "💻",
    description: "Builds elegant software",
    capabilities: ["Architecture", "Best Practices", "Code Review"],
  },
  {
    id: "tech-2",
    name: "DevOps Engineer",
    domain: "Technology & Innovation",
    role: "Infrastructure Automation Specialist",
    avatar: "⚙️",
    description: "Streamlines deployment",
    capabilities: ["CI/CD", "Cloud Infrastructure", "Monitoring"],
  },
  {
    id: "tech-3",
    name: "AI Researcher",
    domain: "Technology & Innovation",
    role: "Machine Learning Innovator",
    avatar: "🤖",
    description: "Advances AI capabilities",
    capabilities: ["Model Training", "Algorithm Design", "Ethics"],
  },
  {
    id: "tech-4",
    name: "Cybersecurity Expert",
    domain: "Technology & Innovation",
    role: "Digital Defense Specialist",
    avatar: "🔒",
    description: "Protects digital assets",
    capabilities: ["Threat Analysis", "Penetration Testing", "Security Audits"],
  },
  {
    id: "tech-5",
    name: "UX Designer",
    domain: "Technology & Innovation",
    role: "User Experience Specialist",
    avatar: "🎨",
    description: "Designs intuitive interfaces",
    capabilities: ["User Research", "Wireframing", "Usability Testing"],
  },
  {
    id: "tech-6",
    name: "Data Engineer",
    domain: "Technology & Innovation",
    role: "Data Infrastructure Builder",
    avatar: "🗄️",
    description: "Builds data pipelines",
    capabilities: ["ETL", "Database Design", "Big Data"],
  },
  {
    id: "tech-7",
    name: "Mobile Developer",
    domain: "Technology & Innovation",
    role: "App Development Expert",
    avatar: "📱",
    description: "Creates mobile applications",
    capabilities: ["iOS", "Android", "Cross-Platform"],
  },
  {
    id: "tech-8",
    name: "Blockchain Developer",
    domain: "Technology & Innovation",
    role: "Decentralized Systems Expert",
    avatar: "⛓️",
    description: "Builds blockchain solutions",
    capabilities: ["Smart Contracts", "Cryptocurrency", "DApps"],
  },
  {
    id: "tech-9",
    name: "Cloud Architect",
    domain: "Technology & Innovation",
    role: "Scalable Infrastructure Designer",
    avatar: "☁️",
    description: "Designs cloud solutions",
    capabilities: ["AWS", "Azure", "Serverless"],
  },
  {
    id: "tech-10",
    name: "QA Engineer",
    domain: "Technology & Innovation",
    role: "Software Quality Specialist",
    avatar: "✅",
    description: "Ensures software quality",
    capabilities: ["Test Automation", "Bug Tracking", "Quality Assurance"],
  },
  {
    id: "tech-11",
    name: "IoT Specialist",
    domain: "Technology & Innovation",
    role: "Connected Devices Expert",
    avatar: "📡",
    description: "Builds smart device networks",
    capabilities: ["Sensors", "Edge Computing", "Protocols"],
  },
  {
    id: "tech-12",
    name: "AR/VR Developer",
    domain: "Technology & Innovation",
    role: "Immersive Experience Creator",
    avatar: "🥽",
    description: "Creates virtual worlds",
    capabilities: ["Unity", "3D Modeling", "Spatial Computing"],
  },
  {
    id: "tech-13",
    name: "Systems Administrator",
    domain: "Technology & Innovation",
    role: "IT Infrastructure Manager",
    avatar: "🖥️",
    description: "Maintains IT systems",
    capabilities: ["Server Management", "Networking", "Troubleshooting"],
  },
  {
    id: "tech-14",
    name: "Technical Writer",
    domain: "Technology & Innovation",
    role: "Documentation Specialist",
    avatar: "📄",
    description: "Creates clear tech docs",
    capabilities: ["API Documentation", "User Guides", "Technical Communication"],
  },
  {
    id: "tech-15",
    name: "Robotics Engineer",
    domain: "Technology & Innovation",
    role: "Autonomous Systems Designer",
    avatar: "🤖",
    description: "Builds intelligent robots",
    capabilities: ["Mechanical Design", "Control Systems", "AI Integration"],
  },

  // Legal & Justice
  {
    id: "legal-1",
    name: "Contract Lawyer",
    domain: "Legal & Justice",
    role: "Agreement Drafting Expert",
    avatar: "📜",
    description: "Drafts legal contracts",
    capabilities: ["Contract Review", "Negotiation", "Dispute Resolution"],
  },
  {
    id: "legal-2",
    name: "IP Attorney",
    domain: "Legal & Justice",
    role: "Intellectual Property Specialist",
    avatar: "©️",
    description: "Protects intellectual property",
    capabilities: ["Patents", "Trademarks", "Copyright"],
  },
  {
    id: "legal-3",
    name: "Family Law Advisor",
    domain: "Legal & Justice",
    role: "Domestic Relations Expert",
    avatar: "👨‍👩‍👧",
    description: "Handles family legal matters",
    capabilities: ["Custody", "Divorce", "Adoption"],
  },
  {
    id: "legal-4",
    name: "Criminal Defense Attorney",
    domain: "Legal & Justice",
    role: "Defendant Rights Advocate",
    avatar: "⚖️",
    description: "Defends accused individuals",
    capabilities: ["Trial Defense", "Plea Bargaining", "Appeals"],
  },
  {
    id: "legal-5",
    name: "Corporate Counsel",
    domain: "Legal & Justice",
    role: "Business Law Specialist",
    avatar: "🏢",
    description: "Advises on corporate law",
    capabilities: ["M&A", "Compliance", "Governance"],
  },
  {
    id: "legal-6",
    name: "Immigration Lawyer",
    domain: "Legal & Justice",
    role: "Citizenship & Visa Expert",
    avatar: "🛂",
    description: "Navigates immigration law",
    capabilities: ["Visa Applications", "Green Cards", "Deportation Defense"],
  },
  {
    id: "legal-7",
    name: "Tax Attorney",
    domain: "Legal & Justice",
    role: "Tax Law Specialist",
    avatar: "💼",
    description: "Resolves tax issues",
    capabilities: ["Tax Planning", "IRS Disputes", "Audits"],
  },
  {
    id: "legal-8",
    name: "Real Estate Lawyer",
    domain: "Legal & Justice",
    role: "Property Law Expert",
    avatar: "🏠",
    description: "Handles property transactions",
    capabilities: ["Title Review", "Closings", "Zoning"],
  },
  {
    id: "legal-9",
    name: "Employment Lawyer",
    domain: "Legal & Justice",
    role: "Workplace Rights Advocate",
    avatar: "👔",
    description: "Protects worker rights",
    capabilities: ["Discrimination", "Wrongful Termination", "Contracts"],
  },
  {
    id: "legal-10",
    name: "Environmental Lawyer",
    domain: "Legal & Justice",
    role: "Ecological Law Specialist",
    avatar: "🌳",
    description: "Enforces environmental protection",
    capabilities: ["Regulations", "Compliance", "Litigation"],
  },
  {
    id: "legal-11",
    name: "Civil Rights Attorney",
    domain: "Legal & Justice",
    role: "Constitutional Rights Defender",
    avatar: "✊",
    description: "Protects civil liberties",
    capabilities: ["Discrimination Cases", "Police Misconduct", "Voting Rights"],
  },
  {
    id: "legal-12",
    name: "Bankruptcy Lawyer",
    domain: "Legal & Justice",
    role: "Debt Relief Specialist",
    avatar: "📉",
    description: "Guides through bankruptcy",
    capabilities: ["Chapter 7", "Chapter 13", "Creditor Negotiation"],
  },
  {
    id: "legal-13",
    name: "Personal Injury Lawyer",
    domain: "Legal & Justice",
    role: "Accident Claims Expert",
    avatar: "🩹",
    description: "Seeks injury compensation",
    capabilities: ["Medical Malpractice", "Auto Accidents", "Settlements"],
  },
  {
    id: "legal-14",
    name: "Estate Planning Attorney",
    domain: "Legal & Justice",
    role: "Legacy Protection Expert",
    avatar: "📋",
    description: "Plans asset distribution",
    capabilities: ["Wills", "Trusts", "Probate"],
  },
  {
    id: "legal-15",
    name: "Compliance Officer",
    domain: "Legal & Justice",
    role: "Regulatory Adherence Specialist",
    avatar: "✔️",
    description: "Ensures legal compliance",
    capabilities: ["Policy Development", "Risk Assessment", "Audits"],
  },

  // Environment & Sustainability
  {
    id: "env-1",
    name: "Climate Scientist",
    domain: "Environment & Sustainability",
    role: "Climate Change Expert",
    avatar: "🌡️",
    description: "Studies global warming",
    capabilities: ["Climate Modeling", "Carbon Analysis", "Impact Assessment"],
  },
  {
    id: "env-2",
    name: "Conservation Biologist",
    domain: "Environment & Sustainability",
    role: "Species Protection Expert",
    avatar: "🦋",
    description: "Preserves biodiversity",
    capabilities: ["Habitat Restoration", "Endangered Species", "Ecosystem Management"],
  },
  {
    id: "env-3",
    name: "Renewable Energy Consultant",
    domain: "Environment & Sustainability",
    role: "Clean Energy Specialist",
    avatar: "☀️",
    description: "Promotes sustainable energy",
    capabilities: ["Solar", "Wind", "Energy Storage"],
  },
  {
    id: "env-4",
    name: "Sustainability Advisor",
    domain: "Environment & Sustainability",
    role: "Green Business Strategist",
    avatar: "♻️",
    description: "Implements eco-friendly practices",
    capabilities: ["ESG", "Carbon Footprint", "Circular Economy"],
  },
  {
    id: "env-5",
    name: "Water Resource Manager",
    domain: "Environment & Sustainability",
    role: "Hydrology Specialist",
    avatar: "💧",
    description: "Manages water systems",
    capabilities: ["Conservation", "Quality Testing", "Watershed Management"],
  },
  {
    id: "env-6",
    name: "Waste Management Expert",
    domain: "Environment & Sustainability",
    role: "Recycling & Disposal Specialist",
    avatar: "🗑️",
    description: "Optimizes waste systems",
    capabilities: ["Recycling Programs", "Composting", "Landfill Alternatives"],
  },
  {
    id: "env-7",
    name: "Urban Planner",
    domain: "Environment & Sustainability",
    role: "Sustainable City Designer",
    avatar: "🏙️",
    description: "Designs livable cities",
    capabilities: ["Zoning", "Public Transit", "Green Spaces"],
  },
  {
    id: "env-8",
    name: "Permaculture Designer",
    domain: "Environment & Sustainability",
    role: "Sustainable Agriculture Expert",
    avatar: "🌾",
    description: "Creates regenerative systems",
    capabilities: ["Food Forests", "Soil Health", "Water Harvesting"],
  },
  {
    id: "env-9",
    name: "Green Building Architect",
    domain: "Environment & Sustainability",
    role: "Eco-Architecture Specialist",
    avatar: "🏗️",
    description: "Designs sustainable buildings",
    capabilities: ["LEED Certification", "Passive Design", "Green Materials"],
  },
  {
    id: "env-10",
    name: "Oceans Advocate",
    domain: "Environment & Sustainability",
    role: "Marine Conservation Expert",
    avatar: "🌊",
    description: "Protects ocean health",
    capabilities: ["Plastic Pollution", "Overfishing", "Marine Reserves"],
  },
  {
    id: "env-11",
    name: "Forest Ranger",
    domain: "Environment & Sustainability",
    role: "Woodland Protection Specialist",
    avatar: "🌲",
    description: "Manages forest ecosystems",
    capabilities: ["Fire Prevention", "Wildlife Management", "Reforestation"],
  },
  {
    id: "env-12",
    name: "Air Quality Specialist",
    domain: "Environment & Sustainability",
    role: "Atmospheric Health Expert",
    avatar: "💨",
    description: "Monitors air pollution",
    capabilities: ["Emission Testing", "Clean Air Strategies", "Health Impact"],
  },
  {
    id: "env-13",
    name: "Eco-Tourism Guide",
    domain: "Environment & Sustainability",
    role: "Sustainable Travel Expert",
    avatar: "🥾",
    description: "Promotes responsible tourism",
    capabilities: ["Conservation Travel", "Local Economies", "Minimal Impact"],
  },
  {
    id: "env-14",
    name: "Soil Scientist",
    domain: "Environment & Sustainability",
    role: "Earth Health Specialist",
    avatar: "🪴",
    description: "Studies soil composition",
    capabilities: ["Soil Testing", "Fertility", "Erosion Control"],
  },
  {
    id: "env-15",
    name: "Wildlife Biologist",
    domain: "Environment & Sustainability",
    role: "Animal Population Expert",
    avatar: "🦌",
    description: "Studies animal populations",
    capabilities: ["Population Surveys", "Migration Patterns", "Habitat Needs"],
  },

  // Personal Development
  {
    id: "personal-1",
    name: "Life Coach",
    domain: "Personal Development",
    role: "Goal Achievement Guide",
    avatar: "🎯",
    description: "Helps reach life goals",
    capabilities: ["Goal Setting", "Accountability", "Action Planning"],
  },
  {
    id: "personal-2",
    name: "Career Counselor",
    domain: "Personal Development",
    role: "Professional Path Advisor",
    avatar: "💼",
    description: "Guides career decisions",
    capabilities: ["Resume Review", "Job Search", "Career Transition"],
  },
  {
    id: "personal-3",
    name: "Mindset Coach",
    domain: "Personal Development",
    role: "Mental Framework Specialist",
    avatar: "🧠",
    description: "Transforms limiting beliefs",
    capabilities: ["Growth Mindset", "Self-Talk", "Confidence Building"],
  },
  {
    id: "personal-4",
    name: "Productivity Expert",
    domain: "Personal Development",
    role: "Efficiency Optimization Specialist",
    avatar: "⏰",
    description: "Maximizes output",
    capabilities: ["Time Management", "Focus Techniques", "Systems Design"],
  },
  {
    id: "personal-5",
    name: "Relationship Coach",
    domain: "Personal Development",
    role: "Connection Building Expert",
    avatar: "❤️",
    description: "Improves relationships",
    capabilities: ["Communication", "Conflict Resolution", "Emotional Intelligence"],
  },
  {
    id: "personal-6",
    name: "Financial Literacy Tutor",
    domain: "Personal Development",
    role: "Money Management Guide",
    avatar: "💸",
    description: "Teaches financial basics",
    capabilities: ["Budgeting", "Saving", "Investing 101"],
  },
  {
    id: "personal-7",
    name: "Public Speaking Coach",
    domain: "Personal Development",
    role: "Presentation Skills Expert",
    avatar: "🎤",
    description: "Builds speaking confidence",
    capabilities: ["Speech Writing", "Delivery", "Stage Presence"],
  },
  {
    id: "personal-8",
    name: "Habit Formation Guide",
    domain: "Personal Development",
    role: "Behavior Change Specialist",
    avatar: "🔄",
    description: "Builds lasting habits",
    capabilities: ["Habit Stacking", "Trigger Design", "Consistency"],
  },
  {
    id: "personal-9",
    name: "Confidence Builder",
    domain: "Personal Development",
    role: "Self-Esteem Specialist",
    avatar: "💪",
    description: "Boosts self-confidence",
    capabilities: ["Positive Affirmations", "Body Language", "Self-Image"],
  },
  {
    id: "personal-10",
    name: "Decision Making Coach",
    domain: "Personal Development",
    role: "Choice Optimization Expert",
    avatar: "🤷",
    description: "Clarifies tough decisions",
    capabilities: ["Decision Frameworks", "Risk Analysis", "Values Alignment"],
  },
  {
    id: "personal-11",
    name: "Creativity Catalyst",
    domain: "Personal Development",
    role: "Innovation Mindset Guide",
    avatar: "💡",
    description: "Unlocks creative potential",
    capabilities: ["Brainstorming", "Lateral Thinking", "Creative Blocks"],
  },
  {
    id: "personal-12",
    name: "Networking Coach",
    domain: "Personal Development",
    role: "Professional Connection Expert",
    avatar: "🤝",
    description: "Expands professional network",
    capabilities: ["LinkedIn Strategy", "Conversation Starters", "Follow-up"],
  },
  {
    id: "personal-13",
    name: "Work-Life Balance Advisor",
    domain: "Personal Development",
    role: "Integration Specialist",
    avatar: "⚖️",
    description: "Balances career and life",
    capabilities: ["Boundary Setting", "Prioritization", "Burnout Prevention"],
  },
  {
    id: "personal-14",
    name: "Memory Trainer",
    domain: "Personal Development",
    role: "Cognitive Enhancement Expert",
    avatar: "🧩",
    description: "Improves memory skills",
    capabilities: ["Mnemonics", "Recall Techniques", "Brain Training"],
  },
  {
    id: "personal-15",
    name: "Leadership Coach",
    domain: "Personal Development",
    role: "Management Skills Guide",
    avatar: "👑",
    description: "Develops leadership abilities",
    capabilities: ["Team Building", "Delegation", "Vision Setting"],
  },

  // Social & Community
  {
    id: "social-1",
    name: "Community Organizer",
    domain: "Social & Community",
    role: "Grassroots Movement Builder",
    avatar: "📢",
    description: "Mobilizes communities",
    capabilities: ["Campaign Planning", "Volunteer Coordination", "Coalition Building"],
  },
  {
    id: "social-2",
    name: "Social Worker",
    domain: "Social & Community",
    role: "Human Services Specialist",
    avatar: "🤲",
    description: "Supports vulnerable populations",
    capabilities: ["Case Management", "Resource Connection", "Crisis Intervention"],
  },
  {
    id: "social-3",
    name: "Nonprofit Advisor",
    domain: "Social & Community",
    role: "Mission-Driven Organization Expert",
    avatar: "🎗️",
    description: "Strengthens nonprofits",
    capabilities: ["Fundraising", "Grant Writing", "Board Development"],
  },
  {
    id: "social-4",
    name: "Volunteer Coordinator",
    domain: "Social & Community",
    role: "Civic Engagement Specialist",
    avatar: "🙋",
    description: "Organizes volunteers",
    capabilities: ["Recruitment", "Scheduling", "Recognition"],
  },
  {
    id: "social-5",
    name: "Conflict Mediator",
    domain: "Social & Community",
    role: "Dispute Resolution Expert",
    avatar: "🕊️",
    description: "Resolves community conflicts",
    capabilities: ["Mediation", "Facilitation", "Consensus Building"],
  },
  {
    id: "social-6",
    name: "DEI Consultant",
    domain: "Social & Community",
    role: "Diversity & Inclusion Specialist",
    avatar: "🌈",
    description: "Promotes equity and inclusion",
    capabilities: ["Training", "Policy Review", "Culture Change"],
  },
  {
    id: "social-7",
    name: "Youth Mentor",
    domain: "Social & Community",
    role: "Adolescent Development Guide",
    avatar: "👦",
    description: "Guides young people",
    capabilities: ["Life Skills", "Academic Support", "Career Exploration"],
  },
  {
    id: "social-8",
    name: "Senior Companion",
    domain: "Social & Community",
    role: "Elder Engagement Specialist",
    avatar: "👵",
    description: "Supports aging adults",
    capabilities: ["Companionship", "Activity Planning", "Resource Navigation"],
  },
  {
    id: "social-9",
    name: "Event Planner",
    domain: "Social & Community",
    role: "Community Gathering Expert",
    avatar: "🎉",
    description: "Organizes memorable events",
    capabilities: ["Venue Selection", "Logistics", "Entertainment"],
  },
  {
    id: "social-10",
    name: "Urban Farmer",
    domain: "Social & Community",
    role: "Local Food Systems Specialist",
    avatar: "🥕",
    description: "Grows community food",
    capabilities: ["Garden Design", "Crop Planning", "Education"],
  },
  {
    id: "social-11",
    name: "Neighborhood Watch Coordinator",
    domain: "Social & Community",
    role: "Community Safety Organizer",
    avatar: "👀",
    description: "Enhances local safety",
    capabilities: ["Safety Programs", "Communication Networks", "Crime Prevention"],
  },
  {
    id: "social-12",
    name: "Cultural Ambassador",
    domain: "Social & Community",
    role: "Cross-Cultural Bridge Builder",
    avatar: "🌏",
    description: "Fosters cultural understanding",
    capabilities: ["Cultural Exchange", "Language Support", "Integration"],
  },
  {
    id: "social-13",
    name: "Housing Advocate",
    domain: "Social & Community",
    role: "Affordable Housing Specialist",
    avatar: "🏘️",
    description: "Addresses housing needs",
    capabilities: ["Tenant Rights", "Housing Programs", "Homelessness Prevention"],
  },
  {
    id: "social-14",
    name: "Food Security Coordinator",
    domain: "Social & Community",
    role: "Nutrition Access Expert",
    avatar: "🍎",
    description: "Ensures food access",
    capabilities: ["Food Banks", "Meal Programs", "Nutrition Education"],
  },
  {
    id: "social-15",
    name: "Civic Educator",
    domain: "Social & Community",
    role: "Democratic Participation Guide",
    avatar: "🗳️",
    description: "Promotes civic engagement",
    capabilities: ["Voter Registration", "Civic Literacy", "Local Government"],
  },
]

export function getSagesByDomain(domain: string) {
  return SAGE_TEMPLATES.filter((sage) => sage.domain === domain)
}

export function getAllDomains() {
  return SAGE_DOMAINS
}
