export type SageDomain =
  | "research"
  | "spirituality"
  | "healthcare"
  | "business"
  | "creativity"
  | "education"
  | "science"
  | "society"

export type SageModality = "text" | "audio" | "video" | "multimodal"

export type SageTone = "scholarly" | "compassionate" | "pragmatic" | "mystical" | "creative" | "analytical"

export interface SageTemplate {
  id: string
  title: string
  domain: SageDomain
  description: string
  role: string
  tone: SageTone
  modality: SageModality
  exampleOutput: string
  capabilities: string[]
  ethicalGuardrails: string[]
  sourceAttachments: string[]
  icon: string
  color: string
}

export const sageTemplates: SageTemplate[] = [
  // Research & Academia (7 templates)
  {
    id: "laboratory-sage",
    title: "Laboratory Sage",
    domain: "research",
    description: "Gathers & summarizes latest papers, validates hypotheses",
    role: "Research Assistant",
    tone: "scholarly",
    modality: "multimodal",
    exampleOutput: "Auto-summarized PubMed reports",
    capabilities: ["literature-review", "hypothesis-testing", "data-analysis", "citation-management"],
    ethicalGuardrails: ["verify-sources", "no-fabricated-data", "cite-all-claims"],
    sourceAttachments: ["PubMed", "arXiv", "Google Scholar"],
    icon: "🔬",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "data-curator",
    title: "Data Curator",
    domain: "research",
    description: "Finds open datasets matching research goals",
    role: "Data Specialist",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Data links + citation table",
    capabilities: ["dataset-discovery", "data-validation", "metadata-generation"],
    ethicalGuardrails: ["respect-data-licenses", "privacy-compliance", "attribution-required"],
    sourceAttachments: ["Kaggle", "Data.gov", "UCI ML Repository"],
    icon: "📊",
    color: "from-purple-500 to-blue-500",
  },
  {
    id: "grant-writer",
    title: "Grant Writer",
    domain: "research",
    description: "Drafts proposals with compliance sections",
    role: "Grant Specialist",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "NIH-formatted draft",
    capabilities: ["proposal-writing", "budget-planning", "compliance-checking"],
    ethicalGuardrails: ["no-plagiarism", "accurate-budgets", "transparent-methodology"],
    sourceAttachments: ["NIH Guidelines", "NSF Requirements"],
    icon: "📝",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "peer-review-assistant",
    title: "Peer-Review Assistant",
    domain: "research",
    description: "Detects logical fallacies, improves clarity",
    role: "Review Specialist",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Review report",
    capabilities: ["logic-analysis", "clarity-improvement", "methodology-review"],
    ethicalGuardrails: ["constructive-feedback", "no-bias", "confidentiality"],
    sourceAttachments: [],
    icon: "🔍",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "research-visualizer",
    title: "Research Visualizer",
    domain: "research",
    description: "Creates AI-generated 'what-if' visuals",
    role: "Visualization Specialist",
    tone: "creative",
    modality: "video",
    exampleOutput: "SORA-rendered simulation",
    capabilities: ["3d-modeling", "animation", "data-visualization"],
    ethicalGuardrails: ["accurate-representations", "no-misleading-visuals"],
    sourceAttachments: ["RunwayML", "Pika"],
    icon: "🎬",
    color: "from-pink-500 to-red-500",
  },
  {
    id: "ethics-reviewer",
    title: "Ethics Reviewer",
    domain: "research",
    description: "Checks experiments for IRB alignment",
    role: "Ethics Specialist",
    tone: "compassionate",
    modality: "text",
    exampleOutput: "Pass/fail summary",
    capabilities: ["ethics-review", "irb-compliance", "risk-assessment"],
    ethicalGuardrails: ["participant-protection", "informed-consent", "privacy-first"],
    sourceAttachments: ["IRB Guidelines", "Belmont Report"],
    icon: "⚖️",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "reference-sage",
    title: "Reference Sage",
    domain: "research",
    description: "Tracks citations & plagiarism",
    role: "Citation Manager",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Zotero-like citation list",
    capabilities: ["citation-tracking", "plagiarism-detection", "bibliography-generation"],
    ethicalGuardrails: ["accurate-citations", "plagiarism-prevention"],
    sourceAttachments: ["Crossref", "DOI"],
    icon: "📚",
    color: "from-teal-500 to-green-500",
  },

  // Spirituality & Well-Being (7 templates)
  {
    id: "zen-sage",
    title: "Zen Sage",
    domain: "spirituality",
    description: "Guides daily meditation via audio/video",
    role: "Meditation Guide",
    tone: "mystical",
    modality: "multimodal",
    exampleOutput: "Morning session clip",
    capabilities: ["guided-meditation", "breath-work", "mindfulness-training"],
    ethicalGuardrails: ["no-medical-claims", "respect-traditions", "inclusive-approach"],
    sourceAttachments: ["ElevenLabs", "Calm API"],
    icon: "🧘",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "chakra-balancer",
    title: "Chakra Balancer",
    domain: "spirituality",
    description: "Recommends practices by emotional input",
    role: "Energy Healer",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Color-coded plan",
    capabilities: ["emotional-assessment", "practice-recommendations", "progress-tracking"],
    ethicalGuardrails: ["no-medical-advice", "respect-beliefs"],
    sourceAttachments: [],
    icon: "🌈",
    color: "from-red-500 to-violet-500",
  },
  {
    id: "mantra-composer",
    title: "Mantra Composer",
    domain: "spirituality",
    description: "Generates personalized chants",
    role: "Sound Healer",
    tone: "mystical",
    modality: "audio",
    exampleOutput: "Audio file with Om frequency",
    capabilities: ["mantra-generation", "frequency-tuning", "voice-synthesis"],
    ethicalGuardrails: ["respect-traditions", "cultural-sensitivity"],
    sourceAttachments: ["ElevenLabs", "Suno"],
    icon: "🕉️",
    color: "from-orange-500 to-yellow-500",
  },
  {
    id: "astrology-interpreter",
    title: "Astrology Interpreter",
    domain: "spirituality",
    description: "Reads natal charts ethically",
    role: "Astrological Consultant",
    tone: "mystical",
    modality: "text",
    exampleOutput: "Planetary insights",
    capabilities: ["chart-reading", "transit-analysis", "interpretation"],
    ethicalGuardrails: ["no-determinism", "empowering-guidance", "entertainment-disclaimer"],
    sourceAttachments: ["Ephemeris Data"],
    icon: "✨",
    color: "from-indigo-500 to-purple-500",
  },
  {
    id: "dream-analyst",
    title: "Dream Analyst",
    domain: "spirituality",
    description: "Symbolically decodes recurring dreams",
    role: "Dream Interpreter",
    tone: "mystical",
    modality: "text",
    exampleOutput: "Archetype summary",
    capabilities: ["symbol-interpretation", "pattern-recognition", "psychological-insights"],
    ethicalGuardrails: ["no-diagnosis", "respect-privacy", "cultural-context"],
    sourceAttachments: ["Jung Archive", "Dream Dictionaries"],
    icon: "🌙",
    color: "from-blue-500 to-purple-500",
  },
  {
    id: "ayurveda-consultant",
    title: "Ayurveda Consultant",
    domain: "spirituality",
    description: "Suggests diet/lifestyle by dosha",
    role: "Ayurvedic Advisor",
    tone: "compassionate",
    modality: "text",
    exampleOutput: "PDF plan",
    capabilities: ["dosha-assessment", "diet-planning", "lifestyle-recommendations"],
    ethicalGuardrails: ["no-medical-claims", "consult-professionals", "cultural-respect"],
    sourceAttachments: ["Ayurvedic Texts"],
    icon: "🌿",
    color: "from-green-500 to-lime-500",
  },
  {
    id: "stoic-companion",
    title: "Stoic Companion",
    domain: "spirituality",
    description: "Offers quotes + reflection prompts",
    role: "Philosophy Guide",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "Daily wisdom feed",
    capabilities: ["quote-curation", "reflection-prompts", "stoic-exercises"],
    ethicalGuardrails: ["authentic-teachings", "practical-application"],
    sourceAttachments: ["Stoic Texts", "Meditations"],
    icon: "🏛️",
    color: "from-gray-500 to-slate-500",
  },

  // Healthcare & Medicine (7 templates)
  {
    id: "surgery-assistant",
    title: "Surgery Assistant",
    domain: "healthcare",
    description: "Visual 'what-if' for complex procedures",
    role: "Surgical Consultant",
    tone: "pragmatic",
    modality: "video",
    exampleOutput: "3D brain-path animation",
    capabilities: ["3d-modeling", "procedure-simulation", "risk-visualization"],
    ethicalGuardrails: ["hipaa-compliance", "licensed-professionals-only", "accurate-anatomy"],
    sourceAttachments: ["Medical Imaging Datasets"],
    icon: "🏥",
    color: "from-red-500 to-pink-500",
  },
  {
    id: "neuro-infection-sage",
    title: "Neuro-Infection Sage",
    domain: "healthcare",
    description: "Advises antibiotic choices",
    role: "Infectious Disease Specialist",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Treatment matrix",
    capabilities: ["treatment-recommendations", "resistance-analysis", "dosing-calculations"],
    ethicalGuardrails: ["evidence-based", "physician-oversight", "patient-safety"],
    sourceAttachments: ["CDC Guidelines", "Clinical Trials"],
    icon: "🧬",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "physiotherapy-coach",
    title: "Physiotherapy Coach",
    domain: "healthcare",
    description: "Generates rehab plans post-surgery",
    role: "Rehab Specialist",
    tone: "compassionate",
    modality: "video",
    exampleOutput: "Video demo set",
    capabilities: ["exercise-planning", "progress-tracking", "video-demonstrations"],
    ethicalGuardrails: ["professional-supervision", "injury-prevention", "individualized-plans"],
    sourceAttachments: ["Exercise Databases"],
    icon: "🤸",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "medical-scribe",
    title: "Medical Scribe",
    domain: "healthcare",
    description: "Converts voice notes → compliant chart",
    role: "Documentation Specialist",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "SOAP note",
    capabilities: ["transcription", "clinical-documentation", "icd-coding"],
    ethicalGuardrails: ["hipaa-compliance", "accurate-transcription", "physician-review"],
    sourceAttachments: ["Whisper API", "Medical Terminology"],
    icon: "📋",
    color: "from-purple-500 to-indigo-500",
  },
  {
    id: "diagnostics-reviewer",
    title: "Diagnostics Reviewer",
    domain: "healthcare",
    description: "Flags anomalies in reports",
    role: "Diagnostic Analyst",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Annotated findings",
    capabilities: ["image-analysis", "pattern-recognition", "anomaly-detection"],
    ethicalGuardrails: ["physician-oversight", "no-diagnosis", "second-opinion-tool"],
    sourceAttachments: ["Medical Imaging"],
    icon: "🔬",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "public-health-tracker",
    title: "Public Health Tracker",
    domain: "healthcare",
    description: "Visualizes disease trends",
    role: "Epidemiologist",
    tone: "analytical",
    modality: "multimodal",
    exampleOutput: "Data map",
    capabilities: ["trend-analysis", "data-visualization", "outbreak-prediction"],
    ethicalGuardrails: ["privacy-protection", "accurate-reporting", "no-panic-inducing"],
    sourceAttachments: ["CDC Data", "WHO Reports"],
    icon: "🌍",
    color: "from-teal-500 to-green-500",
  },
  {
    id: "clinical-research-sage",
    title: "Clinical Research Sage",
    domain: "healthcare",
    description: "Automates literature + trial matching",
    role: "Clinical Researcher",
    tone: "scholarly",
    modality: "text",
    exampleOutput: "Study list",
    capabilities: ["literature-review", "trial-matching", "eligibility-screening"],
    ethicalGuardrails: ["evidence-based", "irb-compliance", "patient-protection"],
    sourceAttachments: ["ClinicalTrials.gov", "PubMed"],
    icon: "🧪",
    color: "from-blue-500 to-purple-500",
  },

  // Business & Productivity (7 templates)
  {
    id: "executive-sage",
    title: "Executive Sage",
    domain: "business",
    description: "Summarizes org data for decisions",
    role: "Executive Assistant",
    tone: "pragmatic",
    modality: "multimodal",
    exampleOutput: "Dashboard brief",
    capabilities: ["data-synthesis", "insight-generation", "decision-support"],
    ethicalGuardrails: ["confidentiality", "unbiased-analysis", "transparent-sources"],
    sourceAttachments: ["Internal Dashboards", "Analytics"],
    icon: "💼",
    color: "from-gray-500 to-blue-500",
  },
  {
    id: "compliance-auditor",
    title: "Compliance Auditor",
    domain: "business",
    description: "Scans docs for policy violations",
    role: "Compliance Officer",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Red-flag report",
    capabilities: ["policy-checking", "risk-assessment", "violation-detection"],
    ethicalGuardrails: ["accurate-flagging", "legal-review", "confidentiality"],
    sourceAttachments: ["Company Policies", "Legal Frameworks"],
    icon: "⚖️",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "customer-success-sage",
    title: "Customer Success Sage",
    domain: "business",
    description: "Monitors sentiment & churn",
    role: "Success Manager",
    tone: "compassionate",
    modality: "text",
    exampleOutput: "Weekly pulse",
    capabilities: ["sentiment-analysis", "churn-prediction", "engagement-tracking"],
    ethicalGuardrails: ["privacy-compliance", "transparent-tracking", "customer-consent"],
    sourceAttachments: ["CRM Data", "Support Tickets"],
    icon: "😊",
    color: "from-green-500 to-blue-500",
  },
  {
    id: "meeting-synthesizer",
    title: "Meeting Synthesizer",
    domain: "business",
    description: "Turns transcripts into action plans",
    role: "Meeting Assistant",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "Summary doc",
    capabilities: ["transcription", "action-item-extraction", "summary-generation"],
    ethicalGuardrails: ["accurate-capture", "participant-consent", "confidentiality"],
    sourceAttachments: ["Whisper API", "Notion"],
    icon: "📝",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "financial-analyst-sage",
    title: "Financial Analyst Sage",
    domain: "business",
    description: "Projects ARR & runway scenarios",
    role: "Financial Analyst",
    tone: "analytical",
    modality: "multimodal",
    exampleOutput: "Forecast chart",
    capabilities: ["financial-modeling", "scenario-planning", "visualization"],
    ethicalGuardrails: ["accurate-calculations", "transparent-assumptions", "professional-review"],
    sourceAttachments: ["Financial Data", "Market Trends"],
    icon: "📈",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "recruitment-advisor",
    title: "Recruitment Advisor",
    domain: "business",
    description: "Screens resumes, structured feedback",
    role: "Talent Acquisition",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "Candidate shortlist",
    capabilities: ["resume-screening", "candidate-matching", "interview-prep"],
    ethicalGuardrails: ["no-bias", "fair-evaluation", "privacy-protection"],
    sourceAttachments: ["ATS Systems"],
    icon: "👥",
    color: "from-blue-500 to-indigo-500",
  },
  {
    id: "negotiation-coach",
    title: "Negotiation Coach",
    domain: "business",
    description: "Simulates counterpart responses",
    role: "Negotiation Consultant",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "Strategy plan",
    capabilities: ["scenario-simulation", "strategy-development", "response-prediction"],
    ethicalGuardrails: ["ethical-tactics", "transparency", "win-win-focus"],
    sourceAttachments: [],
    icon: "🤝",
    color: "from-orange-500 to-red-500",
  },

  // Creativity & Media (7 templates)
  {
    id: "story-weaver",
    title: "Story Weaver",
    domain: "creativity",
    description: "Co-writes novels or scripts",
    role: "Creative Writer",
    tone: "creative",
    modality: "text",
    exampleOutput: "Scene outline",
    capabilities: ["plot-development", "character-creation", "dialogue-writing"],
    ethicalGuardrails: ["original-content", "no-plagiarism", "respectful-themes"],
    sourceAttachments: [],
    icon: "✍️",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "music-muse",
    title: "Music Muse",
    domain: "creativity",
    description: "Generates melodies or lyrics",
    role: "Music Composer",
    tone: "creative",
    modality: "audio",
    exampleOutput: "MIDI or lyric file",
    capabilities: ["melody-generation", "lyric-writing", "arrangement"],
    ethicalGuardrails: ["original-compositions", "copyright-respect"],
    sourceAttachments: ["Suno", "Music Theory"],
    icon: "🎵",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "visual-composer",
    title: "Visual Composer",
    domain: "creativity",
    description: "Concept art via prompt orchestration",
    role: "Visual Artist",
    tone: "creative",
    modality: "multimodal",
    exampleOutput: "AI-rendered frame",
    capabilities: ["image-generation", "style-application", "composition"],
    ethicalGuardrails: ["original-art", "no-copyrighted-styles", "artist-attribution"],
    sourceAttachments: ["Midjourney", "DALL-E"],
    icon: "🎨",
    color: "from-pink-500 to-red-500",
  },
  {
    id: "video-director-sage",
    title: "Video Director Sage",
    domain: "creativity",
    description: "Produces cinematic cuts",
    role: "Video Director",
    tone: "creative",
    modality: "video",
    exampleOutput: "15-sec Runway clip",
    capabilities: ["video-editing", "scene-composition", "effects"],
    ethicalGuardrails: ["original-content", "copyright-compliance", "ethical-themes"],
    sourceAttachments: ["RunwayML", "Pika"],
    icon: "🎬",
    color: "from-red-500 to-orange-500",
  },
  {
    id: "brand-designer",
    title: "Brand Designer",
    domain: "creativity",
    description: "Aligns logo/colors/fonts",
    role: "Brand Consultant",
    tone: "analytical",
    modality: "multimodal",
    exampleOutput: "Style guide",
    capabilities: ["logo-design", "color-theory", "typography"],
    ethicalGuardrails: ["original-designs", "trademark-checking", "accessibility"],
    sourceAttachments: ["Design Systems"],
    icon: "🎨",
    color: "from-purple-500 to-blue-500",
  },
  {
    id: "ad-copy-sage",
    title: "Ad Copy Sage",
    domain: "creativity",
    description: "Multichannel copy variations",
    role: "Copywriter",
    tone: "creative",
    modality: "text",
    exampleOutput: "Campaign draft",
    capabilities: ["copywriting", "a-b-testing", "channel-optimization"],
    ethicalGuardrails: ["truthful-claims", "no-manipulation", "fcc-compliance"],
    sourceAttachments: ["Marketing Data"],
    icon: "📝",
    color: "from-yellow-500 to-orange-500",
  },
  {
    id: "podcast-producer",
    title: "Podcast Producer",
    domain: "creativity",
    description: "Audio clean-up + show notes",
    role: "Audio Producer",
    tone: "pragmatic",
    modality: "audio",
    exampleOutput: "MP3 + summary",
    capabilities: ["audio-editing", "show-notes", "transcription"],
    ethicalGuardrails: ["speaker-consent", "accurate-representation", "copyright-music"],
    sourceAttachments: ["ElevenLabs", "Whisper"],
    icon: "🎙️",
    color: "from-green-500 to-teal-500",
  },

  // Education & Training (7 templates)
  {
    id: "tutor-sage",
    title: "Tutor Sage",
    domain: "education",
    description: "Personalized learning paths",
    role: "Personal Tutor",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Quiz + feedback",
    capabilities: ["lesson-planning", "adaptive-learning", "assessment"],
    ethicalGuardrails: ["accurate-content", "age-appropriate", "inclusive-teaching"],
    sourceAttachments: ["Educational Databases"],
    icon: "👨‍🏫",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "course-creator",
    title: "Course Creator",
    domain: "education",
    description: "Converts notes into e-learning modules",
    role: "Instructional Designer",
    tone: "pragmatic",
    modality: "multimodal",
    exampleOutput: "Slide deck",
    capabilities: ["curriculum-design", "content-creation", "assessment-design"],
    ethicalGuardrails: ["accurate-content", "plagiarism-free", "accessible-design"],
    sourceAttachments: [],
    icon: "📚",
    color: "from-purple-500 to-pink-500",
  },
  {
    id: "exam-simulator",
    title: "Exam Simulator",
    domain: "education",
    description: "Adaptive tests with hints",
    role: "Assessment Specialist",
    tone: "analytical",
    modality: "text",
    exampleOutput: "MCQ interface",
    capabilities: ["test-generation", "adaptive-difficulty", "feedback-provision"],
    ethicalGuardrails: ["fair-assessment", "learning-focused", "no-stress-inducing"],
    sourceAttachments: ["Question Banks"],
    icon: "📝",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "career-counselor",
    title: "Career Counselor",
    domain: "education",
    description: "Skill gap + job path mapping",
    role: "Career Advisor",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Career report",
    capabilities: ["skill-assessment", "career-pathing", "job-matching"],
    ethicalGuardrails: ["unbiased-advice", "realistic-expectations", "privacy-protection"],
    sourceAttachments: ["Job Market Data"],
    icon: "🎯",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "language-sage",
    title: "Language Sage",
    domain: "education",
    description: "Conversational practice",
    role: "Language Teacher",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Dialogue log",
    capabilities: ["conversation-practice", "grammar-correction", "pronunciation-feedback"],
    ethicalGuardrails: ["cultural-sensitivity", "respectful-dialogue", "accurate-language"],
    sourceAttachments: ["Language Databases"],
    icon: "🗣️",
    color: "from-blue-500 to-purple-500",
  },
  {
    id: "stem-explainer",
    title: "STEM Explainer",
    domain: "education",
    description: "Step-by-step derivations",
    role: "STEM Tutor",
    tone: "analytical",
    modality: "multimodal",
    exampleOutput: "Interactive proof",
    capabilities: ["concept-explanation", "problem-solving", "visualization"],
    ethicalGuardrails: ["accurate-science", "clear-explanations", "encourage-curiosity"],
    sourceAttachments: ["Khan Academy", "Wolfram"],
    icon: "🔬",
    color: "from-cyan-500 to-blue-500",
  },
  {
    id: "ai-literacy-guide",
    title: "AI Literacy Guide",
    domain: "education",
    description: "Teaches ethical AI basics",
    role: "AI Educator",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Micro-course",
    capabilities: ["concept-teaching", "ethics-education", "practical-examples"],
    ethicalGuardrails: ["balanced-perspective", "accurate-info", "empowerment-focus"],
    sourceAttachments: ["AI Ethics Guidelines"],
    icon: "🤖",
    color: "from-purple-500 to-indigo-500",
  },

  // Science & Engineering (6 templates)
  {
    id: "simulation-sage",
    title: "Simulation Sage",
    domain: "science",
    description: "Models real-world phenomena",
    role: "Simulation Engineer",
    tone: "analytical",
    modality: "multimodal",
    exampleOutput: "Graph or 3D model",
    capabilities: ["physics-simulation", "data-modeling", "visualization"],
    ethicalGuardrails: ["accurate-models", "validated-assumptions", "transparent-limitations"],
    sourceAttachments: ["Scientific Libraries"],
    icon: "⚗️",
    color: "from-blue-500 to-cyan-500",
  },
  {
    id: "data-pipeline-architect",
    title: "Data Pipeline Architect",
    domain: "science",
    description: "Designs ETL flows",
    role: "Data Engineer",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "DAG diagram",
    capabilities: ["pipeline-design", "optimization", "orchestration"],
    ethicalGuardrails: ["data-privacy", "secure-pipelines", "documentation"],
    sourceAttachments: ["Airflow", "dbt"],
    icon: "🔧",
    color: "from-orange-500 to-red-500",
  },
  {
    id: "code-reviewer",
    title: "Code Reviewer",
    domain: "science",
    description: "Detects bugs + suggests refactors",
    role: "Software Engineer",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Annotated diff",
    capabilities: ["code-analysis", "bug-detection", "refactoring-suggestions"],
    ethicalGuardrails: ["constructive-feedback", "security-focus", "best-practices"],
    sourceAttachments: [],
    icon: "💻",
    color: "from-green-500 to-teal-500",
  },
  {
    id: "cybersecurity-sentinel",
    title: "Cybersecurity Sentinel",
    domain: "science",
    description: "Monitors anomalies in logs",
    role: "Security Analyst",
    tone: "analytical",
    modality: "text",
    exampleOutput: "Threat report",
    capabilities: ["anomaly-detection", "threat-analysis", "incident-response"],
    ethicalGuardrails: ["responsible-disclosure", "privacy-protection", "legal-compliance"],
    sourceAttachments: ["SIEM Tools"],
    icon: "🛡️",
    color: "from-red-500 to-pink-500",
  },
  {
    id: "iot-controller",
    title: "IoT Controller",
    domain: "science",
    description: "Suggests firmware configs",
    role: "IoT Engineer",
    tone: "pragmatic",
    modality: "text",
    exampleOutput: "Command set",
    capabilities: ["device-configuration", "protocol-optimization", "automation"],
    ethicalGuardrails: ["security-first", "privacy-by-design", "safe-defaults"],
    sourceAttachments: ["IoT Protocols"],
    icon: "📡",
    color: "from-purple-500 to-blue-500",
  },
  {
    id: "ai-policy-modeler",
    title: "AI Policy Modeler",
    domain: "science",
    description: "Encodes governance rules",
    role: "Policy Engineer",
    tone: "analytical",
    modality: "text",
    exampleOutput: "OPA policy script",
    capabilities: ["policy-encoding", "rule-validation", "compliance-checking"],
    ethicalGuardrails: ["transparent-rules", "fair-policies", "auditable"],
    sourceAttachments: ["OPA", "Governance Frameworks"],
    icon: "⚖️",
    color: "from-yellow-500 to-orange-500",
  },

  // Society, Art & Culture (2 templates)
  {
    id: "urban-design-sage",
    title: "Urban Design Sage",
    domain: "society",
    description: "Visualizes sustainable city models",
    role: "Urban Planner",
    tone: "creative",
    modality: "video",
    exampleOutput: "3D layout",
    capabilities: ["urban-planning", "sustainability-analysis", "visualization"],
    ethicalGuardrails: ["community-input", "environmental-focus", "equity"],
    sourceAttachments: ["Urban Planning Tools"],
    icon: "🏙️",
    color: "from-green-500 to-blue-500",
  },
  {
    id: "cultural-archivist",
    title: "Cultural Archivist",
    domain: "society",
    description: "Preserves oral histories via agents",
    role: "Archivist",
    tone: "compassionate",
    modality: "multimodal",
    exampleOutput: "Story transcript",
    capabilities: ["oral-history-capture", "transcription", "preservation"],
    ethicalGuardrails: ["cultural-sensitivity", "consent-required", "respectful-representation"],
    sourceAttachments: ["Whisper API", "Archive Systems"],
    icon: "📜",
    color: "from-amber-500 to-orange-500",
  },
]

export const domainInfo = {
  research: {
    name: "Research & Academia",
    description: "Accelerate discovery, validate hypotheses, and manage scholarly work",
    icon: "🔬",
    color: "from-blue-500 to-cyan-500",
  },
  spirituality: {
    name: "Spirituality & Well-Being",
    description: "Guide meditation, balance energy, and nurture inner wisdom",
    icon: "🧘",
    color: "from-purple-500 to-pink-500",
  },
  healthcare: {
    name: "Healthcare & Medicine",
    description: "Support clinical decisions, patient care, and medical research",
    icon: "🏥",
    color: "from-red-500 to-pink-500",
  },
  business: {
    name: "Business & Productivity",
    description: "Optimize operations, enhance decisions, and drive growth",
    icon: "💼",
    color: "from-gray-500 to-blue-500",
  },
  creativity: {
    name: "Creativity & Media",
    description: "Co-create content, design brands, and produce media",
    icon: "🎨",
    color: "from-pink-500 to-red-500",
  },
  education: {
    name: "Education & Training",
    description: "Personalize learning, design curricula, and assess progress",
    icon: "📚",
    color: "from-purple-500 to-indigo-500",
  },
  science: {
    name: "Science & Engineering",
    description: "Model systems, architect data, and secure infrastructure",
    icon: "⚗️",
    color: "from-green-500 to-teal-500",
  },
  society: {
    name: "Society, Art & Culture",
    description: "Design cities, preserve heritage, and shape communities",
    icon: "🌍",
    color: "from-green-500 to-blue-500",
  },
}
